GRANT ALL ON schema public TO postgres;

CREATE TABLE if not exists salute_assistant
(
    id                     bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id                text,
    query_phrase           text,
    pronounce_text         text,
    scenario               character varying(255),
    intent                 character varying(255),
    time_created           timestamp without time zone DEFAULT now(),
    CONSTRAINT salute_assistant_pkey PRIMARY KEY (id)
);

CREATE TABLE if not exists client
(
    id                     bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_name              character varying(255) UNIQUE,
    hobbies                text,
    greeting               text,
    CONSTRAINT client_pkey PRIMARY KEY (id)
);
